# Hours and Expectations

**"Do as I say and not as I do,"** but not with the usual meaning…

In general, we are focused on completing the work that needs to be done, and not on observing a strict schedule. One nice thing about 
research is that, while many tasks such as research appointments or project meetings need to happen at specific places and times, other 
tasks can be more flexibly structured around personal or family obligations (dentist appointments, child or pet care, etc.) or preferences 
around the timing and place of work (e.g., if you prefer to work from home when you can, or are more of a morning or night person). That 
said, our work schedules are subject to two external constraints. The first is that research coordinators and other people in _union-represented_
positions are subject to University-wide policy around things like work hours and overtime. The second is just that we have obligations to our 
funding agencies regarding the work we've promised to do for them, which includes that the effort you devote to those projects should map on 
to what we've allocated for your roles. 

At the same time, there are special research opportunities that you might want to take advantage of (e.g., for career development or other 
personal reasons) that are not directly tied to responsibilities on funded projects, and we wouldn't want to unduly constrain your ability 
to work on those. For this reason, I make a rough distinction between people's **core responsibilities** and their **individual projects.** 
Basically, "core responsibilities" are what we have allocated your funded effort to do: this is usually to work on one of our big R01-funded 
projects, which have pre-specified questions and aims and that will typically extend beyond any single research coordinator's tenure. (As of 
2019: DMA, GBD and Neurotech.) Opportunities for coordinators to do individual original work on these projects are limited. For mentoring, it's
often valuable (but not strictly required) for people to also have independent projects, which allow them more creative room and opportunities 
for learning, ideally leading to first-authored posters and hopefully manuscripts. These should usually be thematically and methodologically 
related to, but non-overlapping with, the questions pursued in our core funded projects. 

For work on **core responsibilities**, research coordinators should generally 
expect to spend no more than 40 hours a week, though with 
some variation week-to-week. If you are regularly spending more than 40 hours a 
week on these responsibilities, this means that something about
your role is misconceived, and please come talk to me about it. You are not required to spend these 40 hours physically on campus, and they 
do not all need to be during normal working hours (if you prefer to work early or late). Now, if research reasons specifically compel you to
work on a weekend, or before about 8am or after 6pm (e.g., to run a participant or set up the scanner), you can and should mark this on your 
timesheet for overtime. (This does not apply to cases in which you simply shift the time of your work, e.g. from morning to evening, because 
of a personal working time preference.)

Work on your **individual projects** is generally not eligible for overtime. You're also welcome to spend time during the normal working day
to pursue these projects, so long as your core responsibilities are taken care of. 

Finally, you will notice that I will send Slack and e-mail messages on nights and weekends, and will be managing work (though at reduced 
efficiency) when I'm on vacation. These all reflect accommodations that I've made in my own working schedule that maximize the time I spend
with my family, but they do not represent expectations for you. So usually, e.g., if I send you a Slack message on the weekend it's because 
I've thought of something that I'm worried I'll forget to tell you if I wait until Monday--_unless I say otherwise_, I'm not expecting a 
response before Monday. (Sometimes questions will come up on a paper or grant deadline that can't actually wait, but I'll let you know and it
shouldn't be often or routine.) And while I take my work with me on vacation, I'm expecting you to actually be off Slack and e-mail while 
you're away--we have enough people in lab that we should be able to make accommodations for covering your responsibilities before you leave.





