# Hiring and Onboarding
Many of our protocols re: creating a ticket to post job openings, the hiring process, and onboarding can be found in the R drive, so I will
just provide links to the appropriate folders/websites here. 

**For lab managers/coordinators tasked with hiring and onboarding new hires:**

* Hiring and Onboarding SOP located in the R-drive: R:\groups\chiong\admin\hiring. This provides an overview of:
  * How to submit tickets to People Connect to create a job requisition for a new position
  * How to get new hires set up with all their UCSF accounts, schedule orientations, and provide a general MAC overview

* Refer to MACipedia as needed

**For new hires:**

* See the 'Guide' document (R:\groups\chiong) for an overview of what's in each folder on the R drive.
* Additional tools and training resources can be found in the R drive: R:\groups\chiong\Resources.
  * Check out 'Training Guide' document for a brief overview of the resources we use.
  * Foundational/interesting articles for key topic areas can be found in the appropriate folders (see "Papers-aging," "Papers-decision-making," etc.)
  * In-depth tutorials on Matlab, STATA, Python, etc.

