--- 
title: "UCSF Decision Lab Handbook"
#author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "Handbook for the UCSF Decision Lab."
---

# Organizing Principles

Early in medical school I received a piece of advice that I have been trying to 
follow since: **Do what you uniquely can do.** 
This of course has different implications for me personally than it does for you 
as a lab member. Let's talk about what it means overall, 
then about what it means for me (since I use this thought to focus our lab's 
work), and then what it means for you individually. 

1. *Overall.* In science there are many questions worth investigating--you can't 
try to study them all or develop expertise in all the 
relevant methods. If you choose questions that everyone else is just as 
well-positioned to answer (i.e., that you're not uniquely 
positioned to answer), then the only way to succeed is to work harder and be 
luckier than everyone else. This is not a sustainable 
path for a career or a life, and probably contributes to the temptations of 
scientific misconduct and non-reproducible practices. 
We all can probably contribute more to science by thinking about what questions 
we're uniquely positioned to answer, whether because 
of our unique backgrounds/skills, temperament and interests, or special 
resources for which we have access that others don't. 

2. *Me and the lab.* Given my interdisciplinary background in neurology and 
philosophy, and given our varied collaborations and the 
especially open culture of the MAC, I believe that our lab is uniquely
 positioned to address questions in neuroscience that also involve 
contributions, methods and insights from the humanities and social sciences. So 
more specifically: decision neuroscience of aging and 
disorders of aging, and neuroethics, and perhaps most of all questions that 
involve both topics together. 

3. *You.* If you're developing an independent research project during your time 
here, I will keep asking you: does this project make 
effective use of methods, populations, resources and frameworks that our lab and 
the MAC are uniquely positioned to utilize? Your time 
here is a brief window during your career, and you should make use of special 
research and learning opportunities you have now that you 
may not have again. More broadly, in preparing for your career after this lab, 
think about where your own particular background, skills 
and interests are most needed and can contribute the most, and use this to
evaluate what other skills you need to pick up along the way 
to maximize your unique contribution. 

In 2018 during the lab's first big hiring wave, Ali Zahir and I tried to 
articulate the essentials of lab culture that we wanted to preserve 
and replicate in our hiring. (So you're all here because we thought you fit the 
following description.) What we decided we were looking for
follows from the principle above. While we think that diversity of experiences 
and perspectives is valuable for all science, it is 
particularly important to our work, and it is also essential that lab members 
value and respect such diversity. We're looking for 
lab members with potential to make unique contributions to lab culture and our 
work--whether in neuroethics, clinical work with patients, neuroscience, 
computation, or logistics. And we are looking for people who, wherever they come 
from, have a track record of making the most of the learning and 
research opportunities available to them. 

In our work, we remain particularly mindful of our obligations to:

**Our funders.** Most of the work in our lab is funded by the National 
Institutes of Health, and of course our infrastructure is provided 
by the University of California. This pays my salary, your salary, travel funds, 
research expenses, equipment, basically everything. 
This ultimately comes from taxes paid by everyone, and thus reflects a 
tremendous public investment in our work--work that should be 
creative, rigorous, and ethical. We strive to be prudent in our management of 
resources, but also aggressive in taking advantage of 
special opportunities to advance science.

**Research participants (and their families).** Our research participants, many 
of whom have serious, stigmatized and/or ultimately fatal 
neurological disorders, expose themselves to research-related risks and 
inconveniences in order to contribute to knowledge that benefits 
society. Ultimately, unproductive (unanalyzed datasets, research products that 
are never shared with the broader scientific community) and 
non-rigorous (sloppy, poorly documented, error-prone) research is unethical, as 
it undermines the social purpose for which participants' 
effort and time are contributed. We also honor participants' contributions by 
treating them with respect, by maintaining our training in 
clinical competence (see below) and safety, by responding promptly to emails and 
other inquiries, and by safeguarding the confidentiality 
of research records.

**The scientific community (particularly our readers).** We aim to contribute to 
a broader project of understanding the brain and the 
ethical issues raised by neuroscience. People who read our papers should find 
their own understanding enhanced by our work. So we use 
reliable and rigorous methods, back up our work to guard against data loss, 
double-check our own work and other lab members' work, 
identify and acknowledge our mistakes, and carefully document what we do. When 
we make discoveries, we help people understand them by 
placing them in appropriate context, avoiding undue hype, acknowledging 
limitations and counterarguments, and writing clearly. We use 
social media, our website, press and other tools to help others (including 
nonspecialists) find our work and so contribute to a broader 
public conversation.

**Colleagues (both in the lab and at MAC/UCSF broadly).** We strive for a lab 
environment in which all members can be successful. 
Discrimination and harassment of all forms are not tolerated--please speak with 
me directly if you are treated in a manner that makes 
you uncomfortable or hinders your ability to work and learn, or observe another 
lab member treated in such a way. We support each other 
and share our knowledge. When there are disagreements or other sources of 
tension, we need to be able to communicate openly about them 
(please again come see me for help with this). We are respectful of one 
another's time and that of our collaborators and research 
participants, so we're punctual and reliable about meetings and appointments. 
That said, please do not come in to work sick. Please 
promote your own health and others' by taking time to recover, making 
arrangements for me and your colleagues to cover for you if 
necessary (they'll be happier doing so than being exposed to whatever you've 
got, and you can return the favor later), and if you absolutely 
need to work doing so remotely.

**Ourselves.** Each of us should feel that we are doing work that we're proud of 
on topics that we're excited about, that we have 
appropriate support, learning opportunities and mentoring to take the next steps 
in our careers, and that we have enough space for the 
people and pursuits that are important to us outside of lab. We also should 
acknowledge that science is inherently hard (we're literally 
trying to do things no one has ever done before), and that you all are in 
particularly vulnerable and stressful parts of your careers. 
Struggling is not a sign of weakness, but is also not something you're expected 
to suffer through by yourself. Please come talk to me 
so we can strategize together about resources, about our mutual expectations, 
about how your work here fits into your broader career goals,
and about how lab work is structured. (I've had many more of these conversations
 with lab members than you probably realize.) Nothing we do
in lab is worth doing if it doesn't also contribute to your health and happiness.

One final quick note about this handbook: at least at present, this handbook is 
for members of the Decision Lab, and is not currently 
intended for dissemination outside the lab.

